# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("7F263D99B929E0B4D25F25B314F1EC0F.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        test.setWindowIcon(icon)
        test.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(test)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 290, 181, 81))
        self.pushButton.setObjectName("pushButton")
        test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(test)
        self.statusbar.setObjectName("statusbar")
        test.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(test)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(test)
        self.actionLoad.setObjectName("actionLoad")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionLoad)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "114514"))
        self.pushButton.setText(_translate("test", "PushButton"))
        self.menu.setTitle(_translate("test", "菜单"))
        self.actionNew.setText(_translate("test", "New"))
        self.actionLoad.setText(_translate("test", "Load"))
import img_rc
